#ifndef JOBENUMS_H
#define JOBENUMS_H

#include "typeDefs.h"

enum e_job_type : uint64
{
	J_A_RECV = 1,
	J_A_SEND = 2,
	J_A_BROADCAST = 3,
	J_A_BROADCAST_PLAYER_MOVE = 4,
	J_A_BROADCAST_PLAYER_SPAWN = 5,
	J_A_BROADCAST_PLAYER_DESPAWN = 6,
	J_A_BROADCAST_PLAYER_DESPAWN_ME = 7,
	J_A_PLAYER_LOGIN = 8,
	J_A_SEND_SPAWN_DATA = 9,
	J_A_PLAYER_VISIT_NEW_SECTION = 10,
	J_A_PLAYER_ENTER_WORLD_FIN = 11,
	
	J_W_PLAYER_ENTER_WORLD= 6001,
	J_W_PLAYER_EXIT_WORLD = 6002,
	J_W_PLAYER_MOVE = 6003,
	J_W_PLAYER_VISIT_NEW_SECTION = 6004,
	J_W_PLAYER_REMOVE = 6005,
	J_W_COLLECT_VISIBLE_ENTER_WORLD= 6006,

	J_MAX 
};


enum e_world_resolve_type :uint64
{
	W_PLAYER_ENTER_ZONE_RESOLVE,
	W_PLAYER_EXIT_ZONE_RESOLVE,
	W_PLAYER_MOVE_RESOLVE,
};
#endif