#ifndef PASSIVITY_ENUMS_H
#define PASSIVITY_ENUMS_H

#include "typeDefs.h"


enum e_passivity_type :uint32
{
	INCREASE_MAX_HP = 1,
	INCREASE_MAX_MP = 2,
	INCREASE_POWER = 3,
	INCREASE_ENDURANCE = 4,
	INCREASE_MOVEMENT_SPEED = 5,
	INCREASE_CRIT_FACTOR = 6,
	INCREASE_DAMAGE_BY = 152,
	INCREASE_IMPACT_FACTOR = 8,
	INCREASE_BALANCE_FACOTR = 9,
	INCREASE_WEAKENING_APPLY_RATE = 10,
	INCREASE_PERIODIC_APPLY_RATE = 11,
	INCREASE_STUN_APPLY_RATE = 12,
	INCREASE_WEAKENING_RESISTANCE = 14,
	INCREASE_PERIODIC_RESISTANCE = 15,
	INCREASE_STUN_RESISTANCE = 16,
	INCREASE_CRIT_POWER = 19,
	SKILLS_PRODUCES_LESS_AGGRO = 20,
	INCREASE_MP_REPLENISHMENT = 21,
	INCREASE_ATTACK_SPEED = 25,
	REOVERS_HP_EVERY_5_SECONDS = 51,
	REOVERS_MP_EVERY_5_SECONDS = 52,
	INCREASE_GATHERING_SKILL = 64,
	INCREASE_PLANT_HARVEST_SPEED = 65,
	INCREASE_GATHERING_SPEED_ARUN = 67,
	INCREASE_ATTACK_SPEED_DECREASE_SKILL_COOLDOWN = 71,
	INCREASE_KNOCKDOWN_RESISTANCE_WHILE_SKILL = 74,
	REFLECT_DAMAGE_TO_ATTACKER = 203,
	INCREASE_CRAFTING_SPEED = 204,
	CHANCE_REPLENISH_MP_COMBAT_ENTER = 207,
	DECREASE_DURATION_OF_STUN = 228, //??
	INCREASE_PVP_DAMAGE = 176,
	DECREASE_PVP_DAMAGE = 113,
	DECREASE_DAMAGE_TAKEN = 102,


	DISSIPATE_EFFECT_ETCHING = 1000,
	DISABLE = 1001,//2 unk
	//MORE TODO

	P_TYPE_MAX
};


#endif
