#ifndef SERVERENUMS_H
#define SERVERENUMS_H

#include "typeDefs.h"

enum serve_request : ulong
{
	NONE = 0,
	CONNEXION = 1
};

enum server_contants : ulong
{
	SC_PLAYER_NAME_MAX_LENGTH = 38,
	SC_PLAYER_MAX_CHARACTER_COUNT = 6,
	SC_PLAYER_DETAILS_1_BUFFER_SIZE = 32,
	SC_PLAYER_DETAILS_2_BUFFER_SIZE = 64,
	SC_PLAYER_DETAILS_3_BUFFER_SIZE = 8,
	SC_CHAT_MESSAGE_MAX_LENGTH = 512,

	SC_AREA_NAME_MAX_LENGTH = 48,
	SC_CHANNELS_PER_AREA = 1,
	SC_PLAYER_VISIBLE_RANGE = 3000,
	SERVER_ID = 1996, //[0xcc07]

	SC_CHAT_MAX_MESSAGE_LENGTH = 270,
	SC_INVENTORY_MAX_SLOTS = 104, //8 * 13
	SC_INVENTORY_MIN_SLOTS = 32, //8 * 4
	SC_INVENTORY_PROFILE_SLOTS_COUNT = 21,
};

enum server_buffer_settings :uint32
{
	SBS_SERVER_MAX_CLIENTS = 1000,
	SBS_CLEINT_SEND_QUEUE_SIZE = 16,
};

#endif // 
